# Generated by Django 2.2 on 2022-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.CharField(choices=[('straight_stair', 'straight_stair'), ('whirlpool_stair', 'whirlpool_stair'), ('emergency_stair', 'emergency_stair'), ('elevator', 'elevator')], default=True, max_length=50),
        ),
    ]
